[tool.poetry]
package-mode = false
name = "dianasproject"
packages = [{include = "."}]

[[tool.poetry.source]]
name="pypi-repository"
url="https://europe-west1-python.pkg.dev/vf-grp-aib-prd-mirror/pypi-repository/simple/"
priority="primary"


[http-basic.pipy-repository]
username = "oauth2accesstoken"
password = "$(gcloud auth print-access-token)"

# 1.2 Dependency management with poetry

[tool.poetry.dependencies]
python = ">=3.10,<3.11.0"
#########################
black = {extras = ["jupyter"],version = "24.2.0"}

